variable "docker_username" {
  description = "Docker Hub username for pulling images"
  type        = string
  sensitive   = true
}

variable "docker_password" {
  description = "Docker Hub password or access token"
  type        = string
  sensitive   = true
}

variable "db_password" {
  description = "Password for PostgreSQL database"
  type        = string
  sensitive   = true
}

variable "secret_key" {
  description = "Secret key for FastAPI application"
  type        = string
  sensitive   = true
}

variable "ssh_public_key" {
  description = "Public key for SSH access to the EC2 instance, generated by the pipeline."
  type        = string
  sensitive   = true
}